pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        // The Nekohasekai repo is optional – it's not used now
        // maven { url 'https://maven.nekohasekai.io/repository/maven-public/' }
    }
}
rootProject.name = "SSH Proxy"
include ':app'